### ISSUE TITLE
Server address in TmcPluginToExistingNetBeans.md slightly incorrect

### ISSUE THREAD

**Issue by BenjaminDeuter** [UniversityHelsinkiTKTL/tmc-plugin-installation-guide#4]
When comparing the [picture](https://cybersecuritybase.github.io/securing/img/tmc-settings.png) from the course with the instructions in the TmcPluginToExistingNetBeans.md file inside this repo, one notices that the server address should be [https://tmc.mooc.fi/org/mooc/](https://tmc.mooc.fi/org/mooc/) not [https://tmc.mooc.fi/org/mooc/](https://tmc.mooc.fi/mooc)

**Comment by nygrenh** [comment]
`tmc.mooc.fi/mooc` is an old server that we're slowly phasing out. I've updated `TmcPluginToExistingNetBeans.md` to be a bit less confusing.
